# utils/file_handler.py

DATA_STORE_PATH = "data/data_store.py"


def save_data(subjects, max_marks, students):
    """
    Rewrites data/data_store.py from scratch with the current
    subjects, max_marks and students, so the data survives after
    the program is closed and reopened.
    """
    lines = []
    lines.append("# data_store.py")
    lines.append("# Auto-generated by utils/file_handler.py -- do not edit by hand.")
    lines.append("")

    # ---- subjects ----
    lines.append("subjects = " + repr(subjects))
    lines.append("")

    # ---- max_marks ----
    lines.append("max_marks = " + repr(max_marks))
    lines.append("")

    # ---- students ----
    lines.append("students = [")
    for student in students:
        lines.append("    " + repr(student) + ",")
    lines.append("]")
    lines.append("")

    file_text = "\n".join(lines)

    file = open(DATA_STORE_PATH, "w")
    file.write(file_text)
    file.close()


def load_data():
    """
    Loads subjects, max_marks and students from data/data_store.py
    by importing it like a normal module.
    """
    import importlib
    import data.data_store as data_store

    importlib.reload(data_store)  # make sure we get the latest saved data
    return data_store.subjects, data_store.max_marks, data_store.students
