# data_store.py
# Auto-generated by utils/file_handler.py -- do not edit by hand.

subjects = ['Maths', 'Science', 'English', 'Computer', 'Social Studies']

max_marks = {'Maths': 100, 'Science': 100, 'English': 100, 'Computer': 100, 'Social Studies': 100}

students = [
    {'roll': 101, 'name': 'Aarav Sharma', 'marks': {'Maths': 85, 'Science': 90, 'English': 78, 'Computer': 95, 'Social Studies': 88}},
    {'roll': 102, 'name': 'Diya Patel', 'marks': {'Maths': 55, 'Science': 48, 'English': 62, 'Computer': 70, 'Social Studies': 59}},
]
